### ISSUE TITLE
请教一下，如何才能自己修改和打包

### ISSUE THREAD

**Issue by Eunknight** [Asvel/octopathtraveler2-zhcn-amend#1]
请教一下大佬，如何才能自己修改和打包。
能否出个简易的修改和打包方法。

有编程基础，没有 UE 和 C 基础。试着安装 Visual Studio，UAssetAPI，UE4 还是没有跑通。

**Comment by Asvel** [comment]
你做了哪些尝试，到哪一步了，具体遇到了什么问题或者报错？

**Comment by Eunknight** [comment]
我的理解是
* 翻译数据文件 **amendments.txt**
* 配置文件 **ot2-zhcn-amend.csproj & ot2-zhcn-amend.sln**
* 核心文件 **Program.cs**

---
流程是修改 amendments.txt，运行 Program.cs 文件，打包出来 octopathtraveler2-zhcn-amend-v2.zip 放在游戏pak目录

Program.cs 文件有 UAssetAPI，我去 UAssetAPI git 下载了，放在了本项目的目录里。
安装了 [Visual Studio 2022] ，UE4.27 
用 Visual Studio 2022 选择  ot2-zhcn-amend.sln 加载了本项目
绿色开始键运行 报错
![1700489801831](https://github.com/Asvel/octopathtraveler2-zhcn-amend/assets/25135978/765dc516-0ba3-43b4-bcb8-66c6648fde67)
![image](https://github.com/Asvel/octopathtraveler2-zhcn-amend/assets/25135978/cd605e79-52d4-445f-a3c9-8bf56a175265)

额外延伸问题
* 如何读取游戏文件 UE4，我加载不了这个游戏的 uasset
* 如何找到 amendments.txt 文件的类似 `TITLE_SYSTEM_LOADING_Text` （文本ID1,文本ID2,文本ID3,或者global）的字段。
* 只能全套搞懂 UE 和 C 才能做 MODE 么？有那种非常适合做 MOD 改 MOD 修改游戏的教程么

**Comment by Asvel** [comment]
UAssetAPI 不要放在子目录，放到和本项目平级的目录，然后先手动打开 UAssetAPI.sln，菜单栏-生成-生成解决方案。

然后这个项目只有修改解包后的资源文件的功能，解包和重新打包需要另外进行。
我用的这个工具：[allcoolthingsatoneplace/UnrealPakTool](https://github.com/allcoolthingsatoneplace/UnrealPakTool)。
打包可能会报错，解决方法可以参考[这个 issue](https://github.com/allcoolthingsatoneplace/UnrealPakTool/issues/10)。
理论上用完整的 UE4 开发环境大概会更好，但我没尝试过这种方案，无法提供比较具体的帮助。

文本ID的获取可以参考程序里的替换逻辑，另外我当时生成了一份翻译对照表：[ot2-texts.zip](https://github.com/Asvel/octopathtraveler2-zhcn-amend/files/13422246/ot2-texts.zip)。

不一定非要全懂，边查边试就好，但最好有基础的计算机程序知识，否则遇到问题很可能会无从下手。
